#!/bin/sh

case "$(echo -e "Shutdown\nRestart\nSuspend\nLock" | dmenu  \
    -nb "${COLOR_BACKGROUND:-#202119}" \
    -nf "${COLOR_DEFAULT:-#bbbbbb}" \
    -sf "${COLOR_HIGHLIGHT:-#eeeeee}" \
    -sb "#3d3e2c" \
    -i -p \
    "Power:" -l 4)" in
        Shutdown) exec systemctl poweroff;;
        Restart) exec systemctl reboot;;
        Suspend) exec systemctl suspend;;
        Lock) exec slock;;
esac
